### ISSUE TITLE
Footer border missing

### ISSUE THREAD

**Issue by kaihendry** [kognise/water.css#173] opened 2020-02-10 07:45 UTC
How come I see a footer rule with `border-top: 1px solid var(--background);` in _misc.css upon https://kognise.github.io/water.css/ but not in view-source:https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.min.css ?

<img src=https://s.natalian.org/2020-02-10/1581320571_2560x1440.png>

**Comment by jonaskuske** [comment] 2020-02-10 10:14
Because the documentation site is using the up-to-date version of `water.css`, while the version available on `cdn.jsdelivr.net` (that is refered to in the docs and README) is very old – version 2.0.0 was completed and merged into `master` early 2019, but not deployed since, so that's been dragged along for almost a year now. Also the reason why many points of the README don't work, which you might have noticed: the CDN links load an outdated version, the link to the version selection is broken because the documentation website isn't up-to-date and doesn't include it yet and the [additional options](https://github.com/kognise/water.css#other-options) also are not available as part of the deploy on `cdn.jsdelivr.net`.

If you want the latest version that also includes the `<footer>` styles:

- clone the repository
- run `npm i` to install dependencies
- run `npm run build`
-  You'll fine the up-to-date stylesheets in the `dist/` folder

If you're confused by the different version you'll find inside `dist/` and need help deciding which one to use, you can refer to the [README](https://github.com/kognise/water.css#other-options) or use the version picker available here: https://deploy-preview-90--watercss.netlify.com/dist/docs/ (just look at the filename at the end of the generated CDN link) 🙂

**Comment by kaihendry** [comment] 2020-02-10 11:42
Thanks!! Though why isn’t jsdelivr updated with the new version? Thanks!

**Comment by kognise** [comment] 2020-05-30 18:50
This has been fixed in the upcoming 2.0 release! Also, I believe it's a duplicate of #160.

**Closed by kognise** 2020-05-30 18:50 UTC
