### ISSUE TITLE
Accesibility: the text inside p tags in light theme is *barely* legible

### ISSUE THREAD

**Issue by thenathurat** [kognise/water.css#55] opened 2019-04-19 16:24 UTC
This is an issue even if this library is used for dead simple html demos. 

It has contrast ratio of only 1.61.

**Comment by thenathurat** [comment] 2019-04-19 16:28
Same with anchor tags - default setting does not work. What does work, is for example #006900.

By default, the contrast ratio is 1.75.

**Comment by kylejrp** [comment] 2019-04-19 16:41
Can you provide a minimal example or a screenshot of what you're seeing? I'm unable to reproduce on the demo page.

Text inside a `<p>` tag is color `#363636` with a background color of `#FFFFFF`, giving a ratio of 12.08.

Text inside a `<a>` tag is color `#0076d1` with a background color of `#FFFFFF`, giving a ratio of 4.65.

What are you seeing on your end?

![image](https://user-images.githubusercontent.com/6742479/56433830-2c9b6800-6287-11e9-9486-0e26e2eeb040.png)

You've brought up great points about accessibility though - I'll do some research and see if this can be a test as part of our build pipeline.

**Comment by thenathurat** [comment] 2019-04-19 16:50
My goodness... 

Yes, I have added water.css to a sample project, however I have forgotten to comment out default styles of another framework. Silly me. 

Okay, so with that silly mistake gone, you are totally right, text inside paragraphs is easily legible and so is inside anchor tags. What could be fixed however, is that everything could be styled to comply with the higher, AAA, standard. 

Currently links are fine according to the AA standard, but not by the AAA. Just a small fix.

**Comment by kylejrp** [comment] 2019-04-19 17:14
Hah, I know I've done the same thing before. No worries!

Great feedback on accessibility - I've opened up #56 and I'll close this issue.

**Closed by kylejrp** 2019-04-19 17:14 UTC
