### ISSUE TITLE
css map is missing

### ISSUE THREAD

**Issue by ewolfe** [kognise/water.css#244] opened 2021-02-01 00:07 UTC
`DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/water.css@2/out/water.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
`

**Comment by eugenesimakin** [comment] 2021-03-17 19:49
Looks like a duplicate of #227

**Closed** 2021-08-11 18:54 UTC
Labels: duplicate
